// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteLocalCommand(arg1) {
  return window['go']['main']['App']['ExecuteLocalCommand'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function NewProject(arg1) {
  return window['go']['main']['App']['NewProject'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RDPTestConnection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RDPTestConnection'](arg1, arg2, arg3, arg4, arg5);
}

export function SSHExecuteCommand(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SSHExecuteCommand'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SSHTestConnection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SSHTestConnection'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveProject(arg1, arg2) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2);
}
