// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {ssh} from '../models';

export function FileExists(arg1:string):Promise<boolean>;

export function LoadProject(arg1:string):Promise<models.TopologyProject>;

export function NewProject(arg1:string):Promise<models.TopologyProject>;

export function OpenFileDialog():Promise<string>;

export function SSHTestConnection(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<ssh.SSHResult>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveProject(arg1:models.TopologyProject,arg2:string):Promise<void>;
