// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {ssh} from '../models';
import {scanner} from '../models';

export function FileExists(arg1:string):Promise<boolean>;

export function LoadProject(arg1:string):Promise<models.TopologyProject>;

export function NewProject(arg1:string):Promise<models.TopologyProject>;

export function OpenFileDialog():Promise<string>;

export function SSHExecuteCommand(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number):Promise<ssh.CommandResult>;

export function SSHReadFile(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function SSHReadLargeFile(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number):Promise<string>;

export function SSHTestConnection(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<ssh.SSHResult>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveProject(arg1:models.TopologyProject,arg2:string):Promise<void>;

export function ScannerCheckDocker(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<scanner.DockerInfo>;

export function ScannerCustomScanPorts(arg1:string,arg2:Array<number>,arg3:number):Promise<Array<scanner.PortInfo>>;

export function ScannerGetSystemInfo(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<scanner.SystemInfo>;

export function ScannerQuickScanPorts(arg1:string,arg2:number):Promise<Array<scanner.PortInfo>>;

export function ScannerRangeScanPorts(arg1:string,arg2:number,arg3:number,arg4:number):Promise<Array<scanner.PortInfo>>;
